### ISSUE TITLE
Failed tests, could not find parser for  'genie.libs.parser.show_bgp.ShowBgpProcessVrfAll'

### ISSUE THREAD

**Issue by annegentle** [virlfiles/genie_learning_lab#8]
In /labs/parsers-with-genie/2.md, ouput after the command robot genie_connect.robot includes this error:
./pyats/lib/python3.6/site-packages/unicon/plugins/nxos/bases.py:22: DeprecationWarning: Arguments 'username', 'enable_password','tacacs_password' and 'line_password' are now deprecated and replaced by 'credentials'. super().__init__(*args, **kwargs)

Failed tests after robot genie_parsers.robot:

Could not find parser for 'genie.libs.parser.show_bgp.ShowBgpProcessVrfAll'
------------------------------------------------------------------------------
execute and parse 'show platform' on UUT                              | FAIL |
Could not find parser for 'genie.libs.parser.show_platform.ShowModule'
------------------------------------------------------------------------------
Genie Parsers                                                         | FAIL |
3 critical tests, 1 passed, 2 failed
3 tests total, 1 passed, 2 failed```

**Comment by syncorpgroup** [comment]
I had the same issue, but I did a workaround. Replace the following sentences in your genie_parsers.robot file. 

But... I would like to know if exist that particular way to call genie parse command with direct access to the library...

 

```
execute and parse 'show bgp process vrf all' on UUT
    # parse "genie.libs.parser.show_bgp.ShowBgpProcessVrfAll" on device "uut"
      parse "show bgp process vrf all" on device "uut"
...
execute and parse 'show platform' on UUT
    # parse "genie.libs.parser.show_platform.ShowModule" on device "uut"
      parse "show module" on device "uut"

```

**Comment by jeaubin** [comment]
Both ways should work   but we are officially encouraging everybody to use the show command way.

We will update the learning lab to reflect this.

Thanks for the feedback

**Comment by danielgraziano** [comment]
Fixed in #9

**Comment by lubnarasheed** [comment]
Thanks for the fix @danielgraziano

**Comment by syncorpgroup** [comment]
Thanks for the fix!
Kevin H.
